- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  # Begin DeltaV modifications - Add time requirement to cargo tech
  # Uncomment once ready to deploy Cargo Assistant
  #requirements:
  #- !type:DepartmentTimeRequirement
  #  department: Logistics # DeltaV - Logistics Department replacing Cargo
  #  time: 21600 # 6 hrs ~3 shifts.
  # End DeltaV modifications
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard

- type: startingGear
  id: CargoTechGear
  equipment:
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff
