- type: entity
  id: MailTeleporterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: mail teleporter machine board
  components:
    - type: Sprite
      state: supply
    - type: MachineBoard
      prototype: MailTeleporter
      stackRequirements:
        Steel: 4
        Cable: 4
        Capacitor: 1
        MatterBin: 1
