name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'PJBot'
    permissions:
      issues: write
      contents: read
      pull-requests: write
    runs-on: mustang
    steps:
    - uses: actions/labeler@v5
